import type { Kpi } from "@/types/kpi"
import type { ExportConfig } from "@/types/export"

export function formatReportDate(): string {
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(new Date())
}

export function defaultTitle(): string {
  return `Financial Overview \u2014 ${formatReportDate()}`
}

export function generateMarkdown(config: ExportConfig, kpis: Kpi[]): string {
  const lines: string[] = []

  lines.push(`# ${config.title}`)
  lines.push(`**${formatReportDate()}**`)
  if (config.subtitle) {
    lines.push(config.subtitle)
  }
  lines.push("")
  lines.push("---")
  lines.push("")
  lines.push("## KPI Summary")
  lines.push("")

  for (const kpi of kpis) {
    const arrow = kpi.change.value >= 0 ? "\u2191" : "\u2193"
    const absChange = Math.abs(kpi.change.value)

    lines.push(`### ${kpi.label}`)
    lines.push(`- **Current:** ${kpi.value}`)
    lines.push(`- **Change:** ${arrow} ${absChange}%`)
    lines.push(`- **Context:** ${kpi.context}`)
    lines.push(`- **Status:** ${kpi.badge?.text ?? "N/A"}`)
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(
    `*Generated by Northscope Dashboard on ${new Date().toISOString()}*`,
  )
  lines.push("")

  return lines.join("\n")
}

export function generateJson(config: ExportConfig, kpis: Kpi[]): string {
  const payload = {
    report: {
      title: config.title,
      subtitle: config.subtitle,
      date: formatReportDate(),
      generatedAt: new Date().toISOString(),
    },
    kpis,
    metadata: {
      source: "Northscope Dashboard",
    },
  }

  return JSON.stringify(payload, null, 2)
}

export function generateExport(
  config: ExportConfig,
  allKpis: Kpi[],
): { content: string; filename: string; mimeType: string } {
  const kpis = allKpis.filter((k) => config.selectedKpiIds.has(k.id))
  const slug = config.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
  const date = new Date().toISOString().split("T")[0]

  if (config.format === "json") {
    return {
      content: generateJson(config, kpis),
      filename: `${slug}-${date}.json`,
      mimeType: "application/json",
    }
  }

  return {
    content: generateMarkdown(config, kpis),
    filename: `${slug}-${date}.md`,
    mimeType: "text/markdown",
  }
}

export function triggerDownload(
  content: string,
  filename: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
